### ISSUE TITLE
Question: can a corpus ever consist of multiple languages?

### ISSUE THREAD

**Issue by bvreede** [elpaco-escience/talkr#31]
Just to determine the granularity of the quality check: they are now being done on
- sources, the original source file with the annotated conversation
- languages, the language the conversation is in
- corpora, a collection of multiple sources

Is it possible that a corpus contains multiple languages? @mdingemanse

**Comment by mdingemanse** [comment]
Excellent question. The way we've organised our data so far this is assumed not to be the case.
But based on the way people use languages, this is definitely possible and in some areas of the world it is even likely.

So: 

- a corpus can contain multiple languages.
- a source can contain utterances in multiple languages (e.g., English and Dutch) — as when people switch languages halfway a conversation
- even an utterance can consist of words and expressions that are from or in multiple languages .
However, we lack data on the latter two: there are very few if any corpora that record language at word or even utterance level.

An ElPaCo corpus for which we've seen a mix of languages is Arapaho, which has some sources that look like plain English and others that seem a different language (i.e., Arapaho). (Do I remember that right, @liesenf?)

Within ElPaCo, we haven't had to worry too much about this because our focus is not so much on precise language identification (we take the corpus at face value). In essence, `language` for us is whatever is reported to be the language spoken in the recorded corpus; so we treat it more like a shorthand for community.

Anyway, what does this mean for the quality checks? I think we would like to know if a given corpus contains material in more than one language, but it does not automatically disqualify the corpus.
